# ===== STAGE 1 : BUILD (Layer-optimisé) =====
FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn -q dependency:go-offline

COPY src ./src

RUN mvn -q package -DskipTests


# ===== STAGE 2 : RUNTIME =====
FROM gcr.io/distroless/java17-debian11:nonroot

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

CMD ["app.jar"]