# ---- Stage 1 : Build TS ----
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build


# ---- Stage 2 : Production distroless ----
FROM gcr.io/distroless/nodejs18

WORKDIR /app

# Copier le build et node_modules depuis le builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

USER 1000

CMD ["dist/server.js"]
